feature-game added: board.py, game.py, player.py
mihaitzzza/nt-06-tic-tac-toe-team-4 pull request #3
Opened 2021-08-23 12:37 UTC by RebecaDumitrascuta

classes were created for: menu, board, player, game
game ready for review

2021-08-23 13:54 UTC, mihaitzzza requested changes

2021-08-23 13:54 UTC, mihaitzzza commented on board.py
> +    def print_board(self):
```
board = Board()
board.print_board()
```
Isn't it much cleaner and easier to read just by doing `board.print()`?

2021-08-23 13:54 UTC, mihaitzzza commented on board.py
> +        print(self.board[7] + '|' + self.board[8] + '|' + self.board[9])
Is there a way to rewrite this without using the positions on the board directly? What if ... for some reason ... you'll name your positions on board with letters? You'll have to do a lot of replacements in this function.

2021-08-23 13:54 UTC, mihaitzzza commented on board.py
> +            return False
`return self.board[position] == ''`

2021-08-23 13:54 UTC, mihaitzzza commented on board.py
> +    def change_board(self, position, character):
Same as the `print` method: `board.change_board()` vs `board.change()`. Also, what about `board.update()`?

2021-08-23 13:54 UTC, mihaitzzza commented on board.py
> +        return None
Why are you returning `None`? Doesn't your function has to return a board? 
- If so, why does it return `None`?
- If not, why does it return a board on L25?

2021-08-23 13:54 UTC, mihaitzzza commented on board.py
> +        winner_lines = [
Do you really want to "create" this variable every time you're calling `is_winner` method? Isn't this a constant?

2021-08-23 13:54 UTC, mihaitzzza commented on board.py
> +    # print(Board().print_board())
Is this comment valuable for further implementation? If not, please remove it.

2021-08-23 13:54 UTC, mihaitzzza commented on board.py
> +    b1 = Board().change_board(9, 'X')
`b1` - not a good name :)

2021-08-23 13:54 UTC, mihaitzzza commented on game.py
> +    def printing_board(self):
Do not use `-ing` in method names.

2021-08-23 13:54 UTC, mihaitzzza commented on game.py
> +    def valid_choices():
These seems to be all the choices on the board, not only the available ones at a point. Also, the method name should express an action: `print`, `show`, `display` etc.

2021-08-23 13:54 UTC, mihaitzzza commented on game.py
> +        self.board.print_board()
Is this easy to be read? :)

2021-08-23 13:54 UTC, mihaitzzza commented on game.py
> +    def modify_board(self, position, character):
`update` is more used than `modify`

2021-08-23 13:54 UTC, mihaitzzza commented on game.py
> +            return self.board.change_board(position, character)
Why are you calling this function twice? Remember function calls are expensive in Python.

2021-08-23 13:54 UTC, mihaitzzza commented on game.py
> +                position = int(input('Not available position, please try again!'))
`input` reads a string - do you have an exception handling here?

2021-08-23 13:54 UTC, mihaitzzza commented on game.py
> +        if num >= 5 and player.total_moves >= 5:
What if the game is won in less then 5 moves?

2021-08-23 13:54 UTC, mihaitzzza commented on game.py
> +def game_application():
Functions should express action: `start_game`, `play` etc.

2021-08-23 13:54 UTC, mihaitzzza commented on menu.py
> +        self.enter_game()
Constructor should be used only for initializing the object. Call `enter_game` in `main.py`.

2021-08-23 13:54 UTC, mihaitzzza commented on menu.py
> +        while self.correct_choice is False:
`not self.correct_choice`

2021-08-23 13:54 UTC, mihaitzzza commented on menu.py
> +            choice_evaluation = self.choice_evaluation()
`evaluate_choice`

2021-08-23 13:54 UTC, mihaitzzza commented on menu.py
> +    def choice_evaluation(self):
`evaluate_choice`

2021-08-23 13:54 UTC, mihaitzzza commented on menu.py
> +    Menu()
This should not be here. Only one entrypoint for the game: `main.py`.

2021-08-23 13:54 UTC, mihaitzzza commented on player.py
> +    total_moves = 0
Why is this a static variable?

2021-08-23 19:42 UTC, RebecaDumitrascuta commented on board.py
> +            return False
is_valid_move - here I test if the cell is available, in my opinion, it needs to have a boolean return

2021-08-23 19:52 UTC, RebecaDumitrascuta commented on board.py
> +    b1 = Board().change_board(9, 'X')
it was just for testing purpose

2021-08-23 19:54 UTC, RebecaDumitrascuta commented on board.py
> +        print(self.board[7] + '|' + self.board[8] + '|' + self.board[9])
wip

2021-08-23 19:55 UTC, RebecaDumitrascuta commented on board.py
> +        return None
under investigation

2021-08-24 08:40 UTC, RebecaDumitrascuta commented on game.py
> +        if num >= 5 and player.total_moves >= 5:
it is possible only if there is only one player. impossible to be won in less then 5 moves when there are 2 players

2021-08-24 08:47 UTC, RebecaDumitrascuta commented on menu.py
> +    Menu()
correct! it was placed there for testing purposes

2021-08-24 08:50 UTC, RebecaDumitrascuta commented on player.py
> +    total_moves = 0
I am using it for counting the objects setter calls. do you have a recommendation ?

2021-08-24 09:41 UTC, mihaitzzza commented on board.py
> +            return False
What's the result of `self.board[position] == ''`?

2021-08-24 09:42 UTC, mihaitzzza commented on player.py
> +    total_moves = 0
`total_moves` are in a game, not as "part" of a player.

2021-08-24 19:05 UTC, RebecaDumitrascuta commented on board.py
> +            return False
for instance: if self.board[5] == 'x', it will return False, 
so it's invalid move, the cell it's not empty, available for move.

2021-08-25 06:41 UTC, mihaitzzza commented on board.py
> +            return False
Sorry, I've forgot a character in my previous comment. So, what's the result of `self.board[position] == '  '` (L18 from your code)?

2021-08-30 18:41 UTC, RebecaDumitrascuta commented on game.py
> -        self.print_cell_labels(),
Did you refer to that comma (,) after self.print_cell_labels ? if yes, I already changed it. it is outdated. I did test it, and I think it worked with that comma, because I have 2 prints

2021-08-31 18:04 UTC, RebecaDumitrascuta commented on player.py
> +    total_moves = 0
I just remove it. I was keeping track of the total_moves at L66 game.py, it was just to enforce the moves counting.

2021-08-31 18:12 UTC, RebecaDumitrascuta commented on board.py
> +            return False
This pice of code is being used in conjuction with: if self.is_valid_move(position):
            self.board[position] = character (L24 board.py), if self.board[position] is not yet ocupied(with [1-9] values), it will return True and the board can be updated with chosen position.

2021-08-31 18:52 UTC, RebecaDumitrascuta commented on board.py
> +            return False
I've added some more additional conditions to this block of code: 
    def is_valid_move(self, position):
        if type(position) is int and position <= 9 and self.board[position] == ' ':
            return True
        else:
            return False

2021-09-02 06:45 UTC, mihaitzzza commented on board.py
> +        if type(position) is int and position <= 9 and self.board[position] == ' ':
You can return directly `type(position) is int and position <= 9 and self.board[position] == ' '` ... it will either return `True` if the condition is met, otherwise it will return `False`. But never mind :)

2021-09-02 06:45 UTC, mihaitzzza approved these changes

2021-09-06 13:30 UTC, merged